### PR TITLE
Add a preference to copy color after picking

### LINKED ISSUE #7: Automatically copy to clipboard
It could be useful to automatically copy the picked value to the clipboard based on a pre-defined preference rather than have to copy using the keyboard shortcut. I can imagine this will differ depending on whether the user needs HEX, RGB, etc. but it would lead to a smoother workflow, especially when integrating with launchers like Raycast (example attached)

https://user-images.githubusercontent.com/48359410/117535038-d6bfc700-afeb-11eb-883a-33bad5ddd7cc.mp4

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #7 

Screen Shot 2021-05-12 at 16 44 03

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm not super happy about the label for the preference. I'm open ideas for improving that.

---

@Clock-Drift @m8ins Would you be willing to try out the build? [Color Picker.app.zip](https://github.com/sindresorhus/System-Color-Picker/files/6465225/Color.Picker.app.zip)

**Comment by Clock-Drift** [comment]
Works well! Perhaps something like 'Default copy value' as the label?

**Comment by sindresorhus** [comment]
> 'Default copy value'

That doesn't make it clear that it copies after picking the color.

**Comment by Clock-Drift** [comment]
I see your point. I think its generally quite intuitive for people using colour pickers for it to either end up in a list in the application window or for it to go to your clipboard automatically but perhaps you could try one of these:

1. Add it in the message in the WelcomeView - e.g. 'System Color Picker automatically copies your selection to the clipboard, set your default value in preferences.'

2. Add a note in the preferences above the menu 'Set a default clipboard/copy value for picked colours'

3. Make it visually obvious if you're averse to cluttering those views:
https://user-images.githubusercontent.com/48359410/117958548-07b53a00-b313-11eb-9c58-ec6bfe91e944.mp4

**Comment by sindresorhus** [comment]
@Clock-Drift Thanks. I'll need to think more about this.

**Comment by sindresorhus** [comment]
Merging now. Gonna come back to improving this later.

**Pull request merged**
